server:
  port: ${PORT:8080}
  
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        platform: postgres
        url: jdbc:postgresql://192.168.1.36:5432/tasks
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: taskPool

management:
    security:
        enabled: false

